#!/usr/bin/env python3
"""Generate the all-MOS/MIM analog ADC wrapper; no behavioral SAR controller."""
from pathlib import Path

HERE=Path(__file__).resolve().parent


def main():
    lines=["* Generated by generate_analog_wrapper.py; deterministic schematic prototype.",
           "* Requires adc_blocks.spice. NOT full ADC qualification.",
           "* SAMPLE/TOP TG opens 10ns before ACQ falls; CONV rises >=20ns after ACQ falls.",
           "* EVAL clock drives dynamic comparator; Q/QB are static retained outputs.",
           ".subckt adc_analog12 INP INN Q QB SAMPLE SAMPLEB ACQ CONV EVAL B11 B10 B9 B8 B7 B6 B5 B4 B3 B2 B1 B0 RP RN VCM VDD VSS",
           "XSP INP TP SAMPLE SAMPLEB VDD VSS adc_tgate", "XSN INN TN SAMPLE SAMPLEB VDD VSS adc_tgate",
           "XCMP TP TN Q QB EVAL VDD VSS adc_latched_comparator"]
    for b in range(12):
        wn=min(8,.84*(2**b)**.5)
        lines += [f"XP{b} BP{b} B{b} ACQ CONV RN RP VCM VDD VSS adc_ref_switch WN={wn:.8g} WP={2*wn:.8g}",
                  f"XN{b} BN{b} B{b} ACQ CONV RP RN VCM VDD VSS adc_ref_switch WN={wn:.8g} WP={2*wn:.8g}"]
    lines += ["XDP DP VDD ACQ CONV RP RN VCM VDD VSS adc_ref_switch",
              "XDN DN VSS ACQ CONV RP RN VCM VDD VSS adc_ref_switch",
              "XCP TP "+" ".join(f"BP{b}" for b in reversed(range(12)))+" DP adc_cdac12",
              "XCN TN "+" ".join(f"BN{b}" for b in reversed(range(12)))+" DN adc_cdac12",
              ".ends adc_analog12"]
    (HERE/'adc_analog12.spice').write_text('\n'.join(lines)+'\n')
    bottom=[]
    for line in lines:
        line=line.replace('adc_analog12','adc_analog12_bottomsample')
        if line.startswith('XSP '):line='XSP VCM TP SAMPLE SAMPLEB VDD VSS adc_tgate'
        elif line.startswith('XSN '):line='XSN VCM TN SAMPLE SAMPLEB VDD VSS adc_tgate'
        elif line.startswith('XCMP '):line='XCMP TN TP Q QB EVAL VDD VSS adc_latched_comparator'
        elif line.startswith('XP') and line[2:3].isdigit():line=line.replace('CONV RN RP VCM','CONV RP RN INP')
        elif line.startswith('XN') and line[2:3].isdigit():line=line.replace('CONV RP RN VCM','CONV RN RP INN')
        elif line.startswith('XDP '):line='XDP DP VSS ACQ CONV RP RN INP VDD VSS adc_ref_switch'
        elif line.startswith('XDN '):line='XDN DN VDD ACQ CONV RP RN INN VDD VSS adc_ref_switch'
        bottom.append(line)
    bottom.insert(1,'* BOTTOM-PLATE sampling candidate: sample input on all bottom plates, clamp top to VCM.')
    bottom.insert(2,'* Comparator inputs reversed so Q keeps same input>=threshold meaning as original.')
    (HERE/'adc_analog12_bottomsample.spice').write_text('\n'.join(bottom)+'\n')
    preamp=[]
    for line in bottom:
        line=line.replace('adc_analog12_bottomsample','adc_analog12_bottom_preamp')
        if line.startswith('XCMP '):
            preamp += ['XPRE TN TP PREP PREN VDD VSS adc_preamp',
                       'XCMP PREP PREN Q QB EVAL VDD VSS adc_latched_comparator']
        else:preamp.append(line)
    preamp.insert(1,'* Experimental preamp isolation candidate; requires adc_preamp.spice in addition to adc_blocks.spice.')
    (HERE/'adc_analog12_bottom_preamp.spice').write_text('\n'.join(preamp)+'\n')
    lvtref=[]
    for line in preamp:
        line=line.replace('adc_analog12_bottom_preamp','adc_analog12_bottom_preamp_lvtref')
        if line.startswith(('XP','XN')) and line[2:3].isdigit():
            b=int(line.split()[0][2:]); wn=min(13.44,.84*(2**b)**.5)
            line=line.split(' adc_ref_switch')[0]+f' adc_ref_switch_lvt WN={wn:.8g} WP={2*wn:.8g}'
        elif line.startswith(('XDP ','XDN ')):
            line=line.replace(' adc_ref_switch',' adc_ref_switch_lvt')
        lvtref.append(line)
    lvtref.insert(1,'* Separate LVT reference-switch candidate; additionally requires adc_reference_candidate.spice. Top clamp remains original standard TG.')
    (HERE/'adc_analog12_bottom_preamp_lvtref.spice').write_text('\n'.join(lvtref)+'\n')


if __name__=='__main__':main()
