#!/usr/bin/env python3
"""Generate a hierarchical, placement-only SKY130 differential CDAC floorplan.

The source CSV files define electrical bank assignment.  This script changes
only physical coordinates, using pitch measured with the exact qualified MIM
PCell.  It intentionally does not draw routing or claim LVS/PEX completion.
"""

from __future__ import annotations

import csv
import hashlib
import json
from collections import Counter
from pathlib import Path


HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
SOURCE_DIR = HERE.parent / "cdac"
PRIMITIVE = REPO / "v2/environment/results/physical_20260908T022855079643Z/mim_unit.mag"
ARTIFACTS = HERE / "artifacts"

# Exact first passing pair pitches from the boundary probe.  Coordinates are
# on Magic's 5 nm internal grid.  X is wider because this PCell's M3 access
# rail protrudes farther laterally than vertically.
PITCH_X_UM = 6.000
PITCH_Y_UM = 4.540
ROWS = 66
COLS = 66
SIDE_GAP_UM = 30.000
PRIMITIVE_BBOX_UM = (-2.430, -1.700, 2.430, 1.700)
MARKER_NETS = ["TOP"] + [f"B{bit}" for bit in reversed(range(12))] + ["DUMMY"]


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_assignment(polarity: str) -> list[dict[str, str]]:
    path = SOURCE_DIR / f"cdac_{polarity.lower()}_assignment.csv"
    with path.open(newline="") as handle:
        rows = list(csv.DictReader(handle))
    if len(rows) != ROWS * COLS:
        raise ValueError(f"{path}: expected {ROWS * COLS} rows, got {len(rows)}")
    if any(row["polarity"] != polarity for row in rows):
        raise ValueError(f"{path}: polarity mismatch")
    coordinates = {(int(row["physical_row"]), int(row["physical_col"])) for row in rows}
    if len(coordinates) != ROWS * COLS:
        raise ValueError(f"{path}: physical coordinates are not one-to-one")
    return rows


def identifier(row: dict[str, str]) -> str:
    return (
        f"X{row['polarity']}_r{int(row['physical_row']):02d}"
        f"_c{int(row['physical_col']):02d}_{row['net']}"
    )


def placement_rows(assignments: dict[str, list[dict[str, str]]]) -> list[dict[str, object]]:
    result: list[dict[str, object]] = []
    for polarity in ("P", "N"):
        for row in assignments[polarity]:
            prow = int(row["physical_row"])
            pcol = int(row["physical_col"])
            result.append(
                {
                    "polarity": polarity,
                    "physical_row": prow,
                    "physical_col": pcol,
                    "core_row": row["core_row"],
                    "core_col": row["core_col"],
                    "net": row["net"],
                    "electrical": int(row["electrical"]),
                    "instance": identifier(row),
                    "local_x_um": pcol * PITCH_X_UM,
                    "local_y_um": prow * PITCH_Y_UM,
                }
            )
    return result


def write_placement_index(rows: list[dict[str, object]]) -> Path:
    path = ARTIFACTS / "placement_index.csv"
    fields = list(rows[0])
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            rendered = dict(row)
            rendered["local_x_um"] = f"{float(row['local_x_um']):.3f}"
            rendered["local_y_um"] = f"{float(row['local_y_um']):.3f}"
            writer.writerow(rendered)
    return path


def getcell_line(row: dict[str, object]) -> str:
    return (
        f"getcell mim_unit child 0 0 parent {row['local_x_um']:.3f}um "
        f"{row['local_y_um']:.3f}um; identify {row['instance']}"
    )


def write_magic_tcl(rows: list[dict[str, object]]) -> Path:
    path = ARTIFACTS / "generate_cdac_floorplan.tcl"
    side_width = (COLS - 1) * PITCH_X_UM + (PRIMITIVE_BBOX_UM[2] - PRIMITIVE_BBOX_UM[0])
    n_origin = side_width + SIDE_GAP_UM
    lines = [
        "# Generated by generate_floorplan.py. Placement-only; no CDAC routing.",
        "set out /repo/v2/physical/cdac_layout_20260911/artifacts",
        "file mkdir $out",
        "cd $out",
        "file copy -force /repo/v2/environment/results/physical_20260908T022855079643Z/mim_unit.mag [file join $out mim_unit.mag]",
        "snap internal",
        "drc off",
        "proc marker {name x y} {",
        "    box values [expr {$x-1.0}]um [expr {$y-1.0}]um [expr {$x+1.0}]um [expr {$y+1.0}]um",
        "    paint metal5",
        "    label $name center metal5",
        "}",
    ]
    for polarity in ("P", "N"):
        cell = f"cdac_side_{polarity.lower()}"
        lines.extend([f"load {cell} -silent", "box values 0 0 0 0"])
        lines.extend(getcell_line(row) for row in rows if row["polarity"] == polarity)
        lines.extend(
            [
                f"save {cell}",
                "select top cell",
                "expand",
                "drc on",
                "drc check",
                "drc catchup",
                f'puts "SIDE_DRC {polarity} [drc list count total]"',
                f"gds write {cell}.gds",
                "drc off",
            ]
        )
    lines.extend(
        [
            "load cdac_diff_floorplan -silent",
            "box values 0 0 0 0",
            "getcell cdac_side_p child 0 0 parent 0um 0um",
            "identify X_CDAC_P",
            f"getcell cdac_side_n child 0 0 parent {n_origin:.3f}um 0um",
            "identify X_CDAC_N",
        ]
    )
    # Put the unconnected planning markers in two vertical columns inside the
    # reserved 30 um routing corridor.  Vertical labels remain readable in a
    # full-floorplan render, unlike a dense horizontal row below the arrays.
    marker_x = {"P": side_width + 2.570, "N": side_width + 17.570}
    marker_y0 = {"P": 5.0, "N": 11.0}
    for polarity in ("P", "N"):
        for index, net in enumerate(MARKER_NETS):
            lines.append(
                f"marker PLAN_{polarity}_{net} {marker_x[polarity]:.3f} "
                f"{marker_y0[polarity] + index * 12.0:.3f}"
            )
    lines.extend(
        [
            "save cdac_diff_floorplan",
            "select top cell",
            "expand",
            "drc on",
            "drc check",
            "drc catchup",
            'puts "FLOORPLAN_DRC_COUNT [drc list count total]"',
            'puts "FLOORPLAN_DRC_DETAILS [drc listall why]"',
            "gds write cdac_diff_floorplan.gds",
            "quit -noprompt",
        ]
    )
    path.write_text("\n".join(lines) + "\n")
    return path


def main() -> None:
    ARTIFACTS.mkdir(parents=True, exist_ok=True)
    assignments = {polarity: read_assignment(polarity) for polarity in ("P", "N")}
    rows = placement_rows(assignments)
    placement = write_placement_index(rows)
    tcl = write_magic_tcl(rows)
    counts = {
        polarity: dict(sorted(Counter(row["net"] for row in assignments[polarity]).items()))
        for polarity in ("P", "N")
    }
    source_files = [
        SOURCE_DIR / "cdac_p_assignment.csv",
        SOURCE_DIR / "cdac_n_assignment.csv",
        SOURCE_DIR / "assignment_summary.json",
        PRIMITIVE,
    ]
    manifest = {
        "generator": Path(__file__).name,
        "evidence_level": "Generated hierarchical placement input; no routing/LVS/PEX",
        "pitch_um": {"x": PITCH_X_UM, "y": PITCH_Y_UM},
        "rows": ROWS,
        "columns": COLS,
        "instances_per_side": ROWS * COLS,
        "instance_counts_by_net": counts,
        "planned_unconnected_pin_markers": 2 * len(MARKER_NETS),
        "source_sha256": {str(path.relative_to(REPO)): sha256(path) for path in source_files},
        "generated_sha256": {path.name: sha256(path) for path in (placement, tcl)},
    }
    (ARTIFACTS / "generation_manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"
    )
    print(json.dumps({"status": "GENERATED", **{k: manifest[k] for k in ("pitch_um", "instances_per_side", "planned_unconnected_pin_markers")}}, indent=2))


if __name__ == "__main__":
    main()
